### ISSUE TITLE
Throwing Deprecation warnings

### ISSUE THREAD

**Issue by tsteuwer** [cibernox/ember-disable-proxy-controllers#1]
So, I just upgraded to 1.12, and I'm getting deprecation warnings which I believe have something to do with this repository.

```
DEBUG: -------------------------------
ember.debug.js:4888DEBUG: Ember      : 1.12.0
ember.debug.js:4888DEBUG: Ember Data : 1.0.0-beta.18
ember.debug.js:4888DEBUG: jQuery     : 1.11.3
ember.debug.js:4888DEBUG: -------------------------------
ember.debug.js:4954DEPRECATION: `lookupFactory` was called on a Registry. The `initializer` API no longer receives a container, and you should use an `instanceInitializer` to look up objects from the container. See http://emberjs.com/guides/deprecations#toc_deprecate-access-to-instances-in-initializers for more details.
        at Object.Registry.lookupFactory (http://localhost/assets/vendor.js:12183:26)
        at ember$data$lib$initializers$store$$initializeStore (http://localhost/assets/vendor.js:70703:48)
        at Object.ember$data$lib$setup$container$$setupContainer [as initialize] (http://localhost/assets/vendor.js:71013:7)
        at http://localhost/assets/vendor.js:14662:23
        at http://localhost/assets/vendor.js:14685:9
        at visit (http://localhost/assets/vendor.js:12701:7)
        at visit (http://localhost/assets/vendor.js:12699:9)
        at DAG.topsort (http://localhost/assets/vendor.js:12813:11)
        at Namespace.default.extend._runInitializer (http://localhost/assets/vendor.js:14684:13)
ember.debug.js:4954DEPRECATION: `lookup` was called on a Registry. The `initializer` API no longer receives a container, and you should use an `instanceInitializer` to look up objects from the container. See http://emberjs.com/guides/deprecations#toc_deprecate-access-to-instances-in-initializers for more details.
        at Object.Registry.lookup (http://localhost/assets/vendor.js:12173:26)
        at ember$data$lib$initializers$store$$initializeStore (http://localhost/assets/vendor.js:70721:28)
        at Object.ember$data$lib$setup$container$$setupContainer [as initialize] (http://localhost/assets/vendor.js:71013:7)
        at http://localhost/assets/vendor.js:14662:23
        at http://localhost/assets/vendor.js:14685:9
        at visit (http://localhost/assets/vendor.js:12701:7)
        at visit (http://localhost/assets/vendor.js:12699:9)
        at DAG.topsort (http://localhost/assets/vendor.js:12813:11)
        at Namespace.default.extend._runInitializer (http://localhost/assets/vendor.js:14684:13)
```

I noticed that this addon uses lookupFactory a ton. Any way to stop this or is there a plan to remove these?

**Comment by cibernox** [comment]
I don't see how this addon can be origin of those deprecation warnings. This addon contains literally 2 files with 4 lines of code in total and no initializers whatsoever.

https://github.com/cibernox/ember-disable-proxy-controllers/tree/master/app/controllers

Just for the record, even if it had deprecation warnings those should never affect your update because this addon won't be necessary in ember 2.0

**Comment by dschmidt** [comment]
Those are Ember Data deprecations which can be fixed by updating it to a more recent version. I guess this can be closed :)
